### ISSUE TITLE
Build Failure with new 2016 index

### ISSUE THREAD

**Issue by Phauly1** [AKSW/AGDISTIS#33]
Hi,

I have cloned the repository and tried to compile AGDISTIS in conjunction with the newly released 2016 index. So, while running `mvn clean install` the `testUmlaute` method failed. If I try it with the old 2014 index, everything will compile just fine and all the tests are passed.

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TripleIndexTest
16:27:00,757 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:01,159 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:01,226 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:01,290 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:01,356 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:01,418 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:01,756 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.238 sec
Running AGDISTISTest
16:27:01,826 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:01,869 INFO [org.aksw.agdistis.webapp.GetDisambiguation] 103 - <	Text: <entity>Masaaki_Ōsumi</entity> works in <entity>Japan</entity>.>
16:27:01,875 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 69 - <	Label: Masaaki_Ōsumi>
16:27:01,976 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 129 - <		number of candidates before type reduction: 137>
16:27:02,022 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 129 - <		number of candidates before type reduction: 328>
16:27:02,046 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 77 - <	Graph size: 0 took: 171 ms>
16:27:02,046 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 69 - <	Label: Japan>
16:27:02,155 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 129 - <		number of candidates before type reduction: 1000>
16:27:02,197 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 77 - <	Graph size: 1 took: 151 ms>
16:27:02,207 INFO [org.aksw.agdistis.algorithm.NEDAlgo_HITS] 67 - <	Graph size before BFS: 1>
16:27:02,288 INFO [org.aksw.agdistis.algorithm.NEDAlgo_HITS] 70 - <	Graph size after BFS: 105>
Japan -> http://dbpedia.org/resource/Japan
Masaaki_Ōsumi -> null
16:27:02,327 INFO [org.aksw.agdistis.util.TripleIndex] 56 - <The index will be here: index>
16:27:02,369 INFO [org.aksw.agdistis.webapp.GetDisambiguation] 103 - <	Text: <entity>Barack Obama</entity> visits <entity>Angela Merkel</entity> in <entity>Berlin</entity>.>
16:27:02,370 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 69 - <	Label: Angela Merkel>
16:27:02,506 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 129 - <		number of candidates before type reduction: 1000>
16:27:02,559 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 77 - <	Graph size: 1 took: 189 ms>
16:27:02,560 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 69 - <	Label: Barack Obama>
16:27:02,640 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 129 - <		number of candidates before type reduction: 1000>
16:27:02,761 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 77 - <	Graph size: 3 took: 201 ms>
16:27:02,761 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 69 - <	Label: Berlin>
16:27:02,846 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 129 - <		number of candidates before type reduction: 1000>
16:27:02,880 INFO [org.aksw.agdistis.algorithm.CandidateUtil] 77 - <	Graph size: 6 took: 118 ms>
16:27:02,881 INFO [org.aksw.agdistis.algorithm.NEDAlgo_HITS] 67 - <	Graph size before BFS: 6>
16:27:03,137 INFO [org.aksw.agdistis.algorithm.NEDAlgo_HITS] 70 - <	Graph size after BFS: 443>
Berlin -> http://dbpedia.org/resource/Berlin
Angela Merkel -> http://dbpedia.org/resource/Angela_Merkel
Barack Obama -> http://dbpedia.org/resource/Barack_Obama
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.376 sec <<< FAILURE!
testUmlaute(AGDISTISTest)  Time elapsed: 0.486 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at AGDISTISTest.testUmlaute(AGDISTISTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running HitsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec
Running PageRankTest
Master:0 H: 1 A: 1 PR: 0,88  ( = 1/5 * 0.15 + 0.85)
Slave1:0 H: 1 A: 1 PR: 0,03  ( = 1/5 * 0.15)
Slave2:0 H: 1 A: 1 PR: 0,03 (usw.)
Slave3:0 H: 1 A: 1 PR: 0,03
Slave4:0 H: 1 A: 1 PR: 0,03
EQUAL1: N1:0 H: 1 A: 1 PR: 0,25
EQUAL2: N1:0 H: 1 A: 1 PR: 0,25
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec

Results :

Failed tests:   testUmlaute(AGDISTISTest)

Tests run: 13, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.934 s
[INFO] Finished at: 2017-01-12T16:27:03+01:00
[INFO] Final Memory: 25M/281M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project AGDISTIS: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ph/Downloads/AGDISTIS/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Best regards

**Comment by DiegoMoussallem** [comment]
yes, please use the mergeT branch and tell me if it is working.

**Comment by DiegoMoussallem** [comment]
@Phauly1, btw, http://dbpedia.org/resource/Masaaki_Ōsumi doesn't exist in 2016-04, so you can ignore this test from 2016 index.

**Comment by Phauly1** [comment]
It is working now after switching to the mergeT branch and changing the index path in the agdistis.property file. Thank you!

When is the new version of AGDISTIS expected to be released?

**Comment by DiegoMoussallem** [comment]
@Phauly1, we are aiming to do it in the end of February.
